### ISSUE TITLE
[Question] Config import to external plugin

### ISSUE THREAD

**Issue by iProdigy** [jack0lantern/raidshamer#2]
Hi Jack!

In [Dink](https://github.com/pajlads/DinkPlugin) we're adding a command that allows users to import settings from other Discord webhook plugins.
A maintainer of another webhook plugin suggested we implement this feature to handle their plugin.

We are currently working on adding support for your plugin; would you have any questions or objections?

**Comment by jack0lantern** [comment]
No problem for me. Just know that if the config changes, you'll have to update yours as well

**Comment by iProdigy** [comment]
Thanks! fyi the migration only copies the settings when the command is run (and doesn't try to keep them in sync), so users theoretically could use both plugins simultaneously with different settings

edit: oh if you meant `RaidShamerConfig` changing, yep that's a good point
